### ISSUE TITLE
Producing "pre" and "code", unexpectedly

### ISSUE THREAD

**Issue by netpoetica** [Shopify/liquid#177]
Using Liquid and Jekyll, my code is producing markup wrapped in "pre" and "code" tags instead of HTML:

``` html
{% for article in page.articles %}
    <div class="eight columns">
        <h3>{{ article.title }}</h3>
        <p>{{ article.desc }}</p>
        <h5><a href="#">Read More</a></h5>
    </div>
{% endfor %}
```

Does anyone know what might cause such a thing? This seems very strange. It's referencing this data in my YAML front matter:

``` yaml
articles: [
    {
        title: '01_art_01',
        desc: 'Lorem ipsum dolor sit amet, consectetur'
    },
    {
        title: '01_art_02',
        desc: 'Lorem ipsum dolor sit'
    },
    {
        title: '01_art_03',
        desc: 'Lorem ipsum dolor sit amet, consectetur'
    },
    {
        title: '01_art_04',
        desc: 'Lorem ipsum dolor sit'
    }
]
```

If this in an intentional behavior, then documentation changes should be in order, and ways around it should be involved in those doc changes!
